"""Default aircraft concept presets for UAV airframe generation."""

from __future__ import annotations

from .models import ConceptPreset

TALON_PUSHER = ConceptPreset(
    id="talon_pusher",
    title="Talon Pusher",
    image_filename="config_pod_boom.jpg",
    wingspan_mm=1400.0,
    wing_root_chord_mm=210.0,
    wing_tip_chord_mm=130.0,
    wing_sweep_deg=2.0,
    wing_dihedral_deg=2.0,
    wing_airfoil="NACA 2412",
    wing_position="High-Wing",
    fuselage_length_mm=850.0,
    fuselage_diameter_mm=130.0,
    nose_length_mm=220.0,
    tail_length_mm=450.0,
    fuselage_style="Pod & Boom",
    tail_type="V-Tail",
    tail_span_mm=380.0,
    tail_root_chord_mm=120.0,
    tail_tip_chord_mm=80.0,
    tail_v_angle_deg=110.0,
    tail_height_mm=160.0,
    tail_arm_mm=520.0,
    tail_airfoil="NACA 0012",
    propulsion_layout="Pusher",
)

CONVENTIONAL_TRACTOR = ConceptPreset(
    id="conventional_tractor",
    title="Conventional Tractor",
    image_filename="config_conventional.jpg",
    wingspan_mm=1600.0,
    wing_root_chord_mm=220.0,
    wing_tip_chord_mm=150.0,
    wing_sweep_deg=0.0,
    wing_dihedral_deg=3.0,
    wing_airfoil="NACA 2412",
    wing_position="High-Wing",
    fuselage_length_mm=1050.0,
    fuselage_diameter_mm=115.0,
    nose_length_mm=250.0,
    tail_length_mm=550.0,
    fuselage_style="Full Fuselage",
    tail_type="Conventional",
    tail_span_mm=440.0,
    tail_root_chord_mm=130.0,
    tail_tip_chord_mm=90.0,
    tail_v_angle_deg=0.0,
    tail_height_mm=180.0,
    tail_arm_mm=650.0,
    tail_airfoil="NACA 0012",
    propulsion_layout="Tractor",
)

TWIN_BOOM_PUSHER = ConceptPreset(
    id="twin_boom_pusher",
    title="Twin-Boom Pusher",
    image_filename="config_twin_boom.jpg",
    wingspan_mm=1800.0,
    wing_root_chord_mm=240.0,
    wing_tip_chord_mm=160.0,
    wing_sweep_deg=0.0,
    wing_dihedral_deg=2.0,
    wing_airfoil="Clark Y",
    wing_position="High-Wing",
    fuselage_length_mm=750.0,
    fuselage_diameter_mm=140.0,
    nose_length_mm=220.0,
    tail_length_mm=350.0,
    fuselage_style="Center Pod",
    tail_type="Twin Boom",
    tail_span_mm=520.0,
    tail_root_chord_mm=120.0,
    tail_tip_chord_mm=90.0,
    tail_v_angle_deg=0.0,
    tail_height_mm=170.0,
    tail_arm_mm=620.0,
    tail_airfoil="NACA 0012",
    propulsion_layout="Pusher",
)

FLYING_WING = ConceptPreset(
    id="flying_wing",
    title="Flying Wing",
    image_filename="config_flying_wing.jpg",
    wingspan_mm=1200.0,
    wing_root_chord_mm=300.0,
    wing_tip_chord_mm=160.0,
    wing_sweep_deg=18.0,
    wing_dihedral_deg=1.0,
    wing_airfoil="MH 45",
    wing_position="Mid-Wing",
    fuselage_length_mm=350.0,
    fuselage_diameter_mm=120.0,
    nose_length_mm=120.0,
    tail_length_mm=150.0,
    fuselage_style="Blended Center Body",
    tail_type="Winglets Only",
    tail_span_mm=0.0,
    tail_root_chord_mm=140.0,
    tail_tip_chord_mm=80.0,
    tail_v_angle_deg=90.0,
    tail_height_mm=160.0,
    tail_arm_mm=0.0,
    tail_airfoil="NACA 0012",
    propulsion_layout="Pusher",
)

CONCEPT_PRESETS: dict[str, ConceptPreset] = {
    TALON_PUSHER.id: TALON_PUSHER,
    CONVENTIONAL_TRACTOR.id: CONVENTIONAL_TRACTOR,
    TWIN_BOOM_PUSHER.id: TWIN_BOOM_PUSHER,
    FLYING_WING.id: FLYING_WING,
}

__all__ = [
    "CONCEPT_PRESETS",
    "CONVENTIONAL_TRACTOR",
    "FLYING_WING",
    "TALON_PUSHER",
    "TWIN_BOOM_PUSHER",
]
