[icons]
error = "error.svg"
warning = "warning.svg"

# File menu
file_open = "project-open-file.png"
file_new = "project-open-file.png"
folder_open = "project-open-folder.png"
project_folder = "project-open-folder.png"
save = "project-save.png"
save_as = "project-save-as.png"
exit = "application-exit.png"

# Edit menu
undo = "edit-undo.png"
redo = "edit-redo.png"
