"""Geometry Engine package for parametric aerodynamics and lofting math."""

from .airfoil import (
    AIRFOIL_SAMPLES,
    AIRFOILS_DATA_DIR,
    PRESET_AIRFOILS,
    apply_airfoil_shaping,
    biconvex,
    compute_airfoil_metrics,
    naca4,
    naca5,
    parse_airfoil_dat,
    sample_airfoil_points,
)
from .data import EnvelopeWireGeometry, GeometryData, LoftGeometry, Point3D, Section
from .envelope import (
    GEOMETRY_COMPONENT_TYPES,
    compute_geometry_envelope,
    sync_component_envelope,
    sync_project_geometry_envelopes,
)
from .fuselage_geometry import (
    DEFAULT_PROFILES,
    FUSELAGE_PROFILE_TYPES,
    SECTION_SAMPLES,
    build_fuselage_geometry,
    compute_section_metrics,
    create_default_section,
    create_default_segment,
    format_profile_size,
    get_default_profile,
    sample_profile,
)
from .lifting_surface_geometry import (
    build_lifting_surface_geometry,
    compute_winglet_projected_dimensions,
)
from .mount import (
    MountFrame,
    MountTarget,
    compute_propeller_clearance,
    generate_clearance_circle_points,
    generate_mount_targets,
    resolve_mount_point,
)
from .transforms import (
    Matrix4,
    derivation_matrix,
    identity_matrix,
    multiply_matrix,
    section_transform,
    transform_matrix,
    transform_point,
)
from .wing_driver_solver import compute_all_8_parameters
from .wing_planform_engine import (
    SWEEP_LOCATIONS,
    TWIST_LOCATIONS,
    calc_tan_sweep_at,
    compute_planform_metrics,
    set_wing_global_dihedral,
    set_wing_global_sweep,
    set_wing_global_twist,
    solve_wing_planform,
)
from .wing_sections_engine import (
    delete_section,
    insert_section,
    profiles_to_sections,
    sections_to_profiles,
    split_section,
)

__all__ = [
    "AIRFOILS_DATA_DIR",
    "AIRFOIL_SAMPLES",
    "DEFAULT_PROFILES",
    "FUSELAGE_PROFILE_TYPES",
    "GEOMETRY_COMPONENT_TYPES",
    "PRESET_AIRFOILS",
    "SECTION_SAMPLES",
    "SWEEP_LOCATIONS",
    "TWIST_LOCATIONS",
    "EnvelopeWireGeometry",
    "GeometryData",
    "LoftGeometry",
    "Matrix4",
    "MountFrame",
    "MountTarget",
    "Point3D",
    "Section",
    "apply_airfoil_shaping",
    "biconvex",
    "build_fuselage_geometry",
    "build_lifting_surface_geometry",
    "calc_tan_sweep_at",
    "compute_airfoil_metrics",
    "compute_all_8_parameters",
    "compute_geometry_envelope",
    "compute_planform_metrics",
    "compute_propeller_clearance",
    "compute_section_metrics",
    "compute_winglet_projected_dimensions",
    "create_default_section",
    "create_default_segment",
    "delete_section",
    "derivation_matrix",
    "format_profile_size",
    "generate_clearance_circle_points",
    "generate_mount_targets",
    "get_default_profile",
    "identity_matrix",
    "insert_section",
    "multiply_matrix",
    "naca4",
    "naca5",
    "parse_airfoil_dat",
    "profiles_to_sections",
    "resolve_mount_point",
    "sample_airfoil_points",
    "sample_profile",
    "section_transform",
    "sections_to_profiles",
    "set_wing_global_dihedral",
    "set_wing_global_sweep",
    "set_wing_global_twist",
    "solve_wing_planform",
    "split_section",
    "sync_component_envelope",
    "sync_project_geometry_envelopes",
    "transform_matrix",
    "transform_point",
]
