"""Unit system presets (SI, Aviation, Imperial)."""

from __future__ import annotations

PRESETS: dict[str, dict[str, str]] = {
    "si": {
        "name": "Metric (SI Standard)",
        "length": "mm",
        "area": "dm2",
        "volume": "dm3",
        "mass": "g",
        "angle": "deg",
        "velocity": "m/s",
        "force": "N",
        "torque": "N*m",
        "pressure": "Pa",
        "power": "W",
        "voltage": "V",
        "current": "A",
        "capacity": "mAh",
        "resistance": "ohm",
        "inertia": "kg*m2",
        "wing_loading": "g/dm2",
        "frequency": "rpm",
        "density": "kg/m3",
    },
    "aviation": {
        "name": "Aviation Standard",
        "length": "mm",
        "area": "dm2",
        "volume": "l",
        "mass": "g",
        "angle": "deg",
        "velocity": "kts",
        "force": "kgf",
        "torque": "kgf*cm",
        "pressure": "mbar",
        "power": "W",
        "voltage": "V",
        "current": "A",
        "capacity": "mAh",
        "resistance": "mohm",
        "inertia": "kg*m2",
        "wing_loading": "g/dm2",
        "frequency": "rpm",
        "density": "kg/m3",
    },
    "imperial": {
        "name": "Imperial (US Customary)",
        "length": "in",
        "area": "ft2",
        "volume": "in3",
        "mass": "lb",
        "angle": "deg",
        "velocity": "mph",
        "force": "lbf",
        "torque": "lbf*in",
        "pressure": "psi",
        "power": "hp",
        "voltage": "V",
        "current": "A",
        "capacity": "Ah",
        "resistance": "ohm",
        "inertia": "lb*in2",
        "wing_loading": "oz/ft2",
        "frequency": "rpm",
        "density": "lb/ft3",
    },
}

__all__ = ["PRESETS"]
